//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryMVCProjects.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Books
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Books()
        {
            this.Operations = new HashSet<Operations>();
        }
    
        public int Id { get; set; }
        [Display(Name ="WriterName")]
        [Required(ErrorMessage ="WriterName boþ geçilemez")]
        public Nullable<int> WriterId { get; set; }
        [Display(Name = "TypeName")]
        [Required(ErrorMessage = "TypeName boþ geçilemez")]
        public Nullable<int> BookTypeId { get; set; }
        [Required(ErrorMessage = "Page boþ geçilemez")]
        [Range(0,2000)]
        public Nullable<int> Page { get; set; }
        [Required(ErrorMessage = "BookName boþ geçilemez")]
        public string BookName { get; set; }
    
        public virtual BookTypes BookTypes { get; set; }
        public virtual Writers Writers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Operations> Operations { get; set; }
    }
}
