//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryMVCProjects.Models.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LibraryBackendsEntities : DbContext
    {
        public LibraryBackendsEntities()
            : base("name=LibraryBackendsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Books> Books { get; set; }
        public virtual DbSet<BookTypes> BookTypes { get; set; }
        public virtual DbSet<Operations> Operations { get; set; }
        public virtual DbSet<Students> Students { get; set; }
        public virtual DbSet<Writers> Writers { get; set; }
        public virtual DbSet<Userss> Userss { get; set; }
    }
}
