//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryMVCProjects.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operations
    {
        public int Id { get; set; }
        public Nullable<int> StudentId { get; set; }
        public Nullable<int> BookId { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
    
        public virtual Books Books { get; set; }
        public virtual Students Students { get; set; }
    }
}
