//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryMVCProjects.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Operations
    {
        public int Id { get; set; }
        [Display(Name ="StudentName")]
        [Required(ErrorMessage = "StudentName boþ geçilemez")]
        public Nullable<int> StudentId { get; set; }
        [Display(Name = "BookName")]
        [Required(ErrorMessage = "BookName boþ geçilemez")]
        public Nullable<int> BookId { get; set; }
        [Display(Name = "BookName")]
        [Required(ErrorMessage = "Price boþ geçilemez")]
        public Nullable<int> Price { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
    
        public virtual Books Books { get; set; }
        public virtual Students Students { get; set; }
    }
}
